lib/blog_web/router.ex
defmodule BlogWeb.Router do
  use BlogWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug BlogWeb.Plugs.SetUser
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", BlogWeb do
    pipe_through :browser # Use the default browser stack
    get "/", BlogController, :index
    get "/iriguchi", SessionController, :new
    post "/iriguchi", SessionController, :create
    get "/logout", SessionController, :delete
    resources "/blogs", BlogController#, except: [:index]
    get "/feedback", MailController, :new
    post "/feedback", MailController, :create
    get "/users/", UserController, :new
    post "users/", UserController, :create
  end

  # Other scopes may use custom stacks.
  # scope "/api", BlogWeb do
  #   pipe_through :api
  # end
end

lib/blog_web/views/layout_view.ex
defmodule BlogWeb.LayoutView do
  use BlogWeb, :view
end

lib/blog_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Blog</title>
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/css/materialize.min.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/prism.css") %>">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/highlight.js/latest/styles/github.min.css">
  </head>

  <body>
    <nav class="navbar hoverable">
      <span class="exit-btn right">
        <%= if admin?(@conn) do %>
        <%= link to: session_path(@conn, :delete), class: "btn-floating hoverable btn-large waves-effect waves-light red" do %>
          <i class="material-icons">exit_to_app</i>
        <% end %>
        <% end %>
      </span>
      <div class="nav-wrapper container">
        <span class="right">
          <i class="material-icons">email</i>
        </span>
        <span class="right">
          <%= link "Обратная связь ", to: mail_path(@conn, :new) %>
        </span>
        <span class="brand-logo center">Yet Another Blog</span>
      </div>

    </nav>
    <main role="main">
      <div class="container">
        <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
        <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>
        <%= render @view_module, @view_template, assigns %>
      </div>
    </main>

    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
    <script src="<%= static_path(@conn, "/js/prism.js") %>"></script>
    <script src="https://cdn.jsdelivr.net/highlight.js/latest/highlight.min.js"></script>
  </body>
</html>